### ISSUE TITLE
posted item cards removes non-breaking spaces.

### ISSUE THREAD

**Issue by sonicfan315** [moo-man/WrathAndGlory-FoundryVTT#10]
Posting item cards with non-breaking spaces removes the formatting, and displays nbsp characters instead.

![FoundryVTT_BrpudcwJcW](https://user-images.githubusercontent.com/81267252/112224642-8cc88080-8bf9-11eb-834c-4ea95f5c88b5.png)

**Comment by moo-man** [comment]
Cannot reproduce this now so I assume it was fixed at some point.
