### ISSUE TITLE
Can't add keyword to agent

### ISSUE THREAD

**Issue by Guillaume-Duc-95** [moo-man/WrathAndGlory-FoundryVTT#12]
Hi there! First of all thank you for this module.

I can't find where to add the keywords so they show up at the bottom of the `stats` tab.

**Comment by DrathVenrir** [comment]
You have to add them in the "items" tab. From there after you have entered
them, you can drag them from that bar onto the character sheet. I'm active
on Discord and I am running a game, if you need help let me know Darth
Venrir#1994. I'm not a creator, but I am very invested in Moo Man's work
and I try and help were I can. Cheers!

**Comment by Guillaume-Duc-95** [comment]
Thanks! It worked, but I still find unintuitive the way to add the keywords.

**Comment by DrathVenrir** [comment]
I'm sure mooman will fix it when he can, I've chatted with him, he is
ALWAYS busy working on several projects. But he is awesome and I'm sure
he'll continue to give us a great system. Hit me up on discord of you need
anything!
