### ISSUE TITLE
Weapon traits

### ISSUE THREAD

**Issue by Dark-Elyrion** [moo-man/WrathAndGlory-FoundryVTT#121]
Hi,

I'm opening it again, sorry.
But I can't seems to find a way to enter a new traits for a weapon.
There is no options to create a trait in the compendium, or in the objects.
The Custom trait don't seems to work.

Is it beacause we have to create an effect on a weapon upgrade with an effect "trait" ?
Anything else ?

I'm new at this and a little lost...

Sorry again and thank you for your hard work!

Kind regards,

Dark Elyrion

**Comment by moo-man** [comment]
When you say Custom traits don't work, did you follow the format specified in the tooltip?

**Comment by Dark-Elyrion** [comment]
Tooltip ?

**Comment by moo-man** [comment]
Yes, there's a tooltip on the custom traits input that describes how to format your input.

**Comment by Dark-Elyrion** [comment]
When I go to item traits, i see the Custom trait appear but I can't do anything. When I write something, it won't appear on the weapon. And when I click on custom trait, it does nothing.

I don't see a toolip (I don't know what it looks like ^^')

![image](https://user-images.githubusercontent.com/105993661/169669202-f57f727d-124f-4d77-864b-ad38f2e3a55d.png)

**Comment by moo-man** [comment]
Hover over the Custom Traits input

**Comment by Dark-Elyrion** [comment]
It does nothing...

Same for the others. Is it maybe because I have some modules that block it ?

**Comment by moo-man** [comment]
I'm not sure.

Here's the format you should follow: `Trait 1: Trait 1 Description | Trait 2: Trait 2 Description | etc.`

Closing this, feel free to reopen if there's still an issue.

**Comment by Dark-Elyrion** [comment]
Thank you again for your time and help. I will post if there is.

**Comment by Dark-Elyrion** [comment]
Well I manage to relod my page and purge and reinstall all and it worked fine.

Sorry for the inconvenience, it work fine, it appear now.

Thank you so much and have a nice day/night
