### ISSUE TITLE
Wrath Complations not working

### ISSUE THREAD

**Issue by TomChristoffer** [moo-man/WrathAndGlory-FoundryVTT#124]
Wrath complications chat buttons do not do anything, gives data reading error.

**Comment by moo-man** [comment]
Can you provide more details on what this error was?

**Comment by TomChristoffer** [comment]
> Can you provide more details on what this error was?

Sorry I was unavailable for a few days:
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'data')
[Detected 1 package: system:wrath-and-glory]
    at Function._onWrathClick (systems/wrath-and-glory/scripts/common/chat.js:60)
    at HTMLElement.dispatch (jquery.min.js:2)
    at HTMLElement.v.handle (jquery.min.js:2)
