### ISSUE TITLE
Floating Text Boxes

### ISSUE THREAD

**Issue by Ocule** [moo-man/WrathAndGlory-FoundryVTT#14]
Boxes for Faith on the Combat page, as well as Influence and Wealth on the Gear page are not anchored to a point on the page like the other boxes and scroll with the user causing difficulty reading when scrolling because they overlap the other boxes. It's still legible when scrolled all the way up on the relevant tab

**Comment by moo-man** [comment]
Can you provide a screenshot? I'm not quite following how to reproduce

**Comment by Ocule** [comment]
Sure, here is where the influence and wealth boxes are. Second image shows them when im scrolled all the away up. 
![image](https://user-images.githubusercontent.com/44648047/120399714-8eee4000-c30a-11eb-8d63-384995b6c194.png)
![image](https://user-images.githubusercontent.com/44648047/120399861-d2e14500-c30a-11eb-8ac7-b3fd08eb7e39.png)

**Comment by moo-man** [comment]
Well, I'm not seeing the same thing here. Somehow your whole sheet is scrolling

![image](https://user-images.githubusercontent.com/28637157/120400122-ea1c3480-c302-11eb-9fce-a0133413aef6.png)

**Comment by Vendare** [comment]
It only happens on low resoltions. If the space it not big enough to display it's prefered size the window content area itself becomes scrollable. 
![image](https://user-images.githubusercontent.com/6638899/124508896-10853200-ddd1-11eb-8185-bbb54dc89ca9.png) 
Running at 1366x738

Adding a lot of items we get a second scrollable area this behaves just as we want it to like you demonstrate with your screenshot.
![image](https://user-images.githubusercontent.com/6638899/124510432-0dd80c00-ddd4-11eb-8fe3-416c7f6ab25b.png)
Notice the shifted Influence and Wealth Fields though. They seem to be ancored to the window itself not the content area.
