### ISSUE TITLE
[Wrath & Glory: Core Module] Update to V10 283 with W&G V 4

### ISSUE THREAD

**Issue by moo-man** [moo-man/WrathAndGlory-FoundryVTT#142]
Auto Calculate functions broken, For both Core characters and Forsaken Guide.<br/>**From**: kkrems@sbcglobal.net<br/>wrath-and-glory: 4.0.0

**Comment by RedBeardRandoms** [comment]
Having done some testing, it seems like the auto calculations break whenever a talent or buff tries to interact with any variable on the sheet. For Example, Uncanny [Trait] or Acute Senses break the calculation. Specifically, it seems to be the @advances.rank variable that causes a problem, as I have replaced it with a number and it instantly worked again.

**Comment by Tidman1000** [comment]
The experience point calculations when updating character sheets are also adding incorrectly. 
Going from a stat store of 1 to 2 is showing a cost of 8 points when it should be 4.

**Comment by moo-man** [comment]
fixed via https://github.com/moo-man/WrathAndGlory-FoundryVTT/commit/4d61837fff9b4c3ffe179b3e7d3d73d25546773b and https://github.com/moo-man/WrathAndGlory-FoundryVTT/commit/cc51658a6da13b1100c12b9c1b9c6a37dfb276d2

Related #154 
Related #149 

Closing as duplicate to related
