### ISSUE TITLE
Threat traits not always matching listing in the rules due to auto-calculated results.

### ISSUE THREAD

**Issue by maddoodles** [moo-man/WrathAndGlory-FoundryVTT#143]
**Describe the bug**
Some threats, such as the Space Marine's Resolve, are listed incorrectly as Threat sheets still default to automatic calculation, where their stats in the book could not be achieved by the regular calculation methods. I can attempt to produce a full list at some point, as I have not gone through every single entry yet. I have already seen, however:

- Imperial Citizen (Should be Conviction 2, Resolve 1, is Conviction 3, Resolve 2)
- Veteran Sergeant (All Traits incorrect other than Shock and Defence)
- Tactical Space Marine ( Should be Resolve 4, is Resolve 3)
- Servo Skull (Should be Defence 5, is Defence 3)

That actually covers it for Imperial Threats as far as I can tell.

**Version Numbers**
Foundry: v9 Build 280
wrath-and-glory: 3.6.1

**Comment by moo-man** [comment]
I think I did this on purpose, to match the formula as I assumed the calculations were just typos.

**Comment by maddoodles** [comment]
Hmm, I'm kind of in two minds about that.

On one hand, I actually do agree it makes sense to keep it consistent, and will likely keep running things that way myself. However, I'm not sure if that's a decision that should be made for GMs preemptively, particularly as if a GM makes changes, those changes will be wiped with an update (at least that's how it's gone for me, although so far I've just been using custom icons for things for variety).

This is work that you're doing directly for Cubicle7 right? We're certainly paying them for it (and I'd hope they're paying you! 😂), do you not have a more direct line to possibly get rules clarifications like that? I feel like that's a relatively important thing to iron out.

Anyway, those are just my thoughts, thank you for getting back so quickly.

**Comment by moo-man** [comment]
I generally don't ask for clarifications as I think it would open the flood gates and set the precedent for the Foundry systems to be a sort of "errata" that I want to avoid.

That might seem contradictory when I use the "correct" calculations, I'm not really sure I have a good justification for it, just that simple typos (especially ones that involve math) aren't a huge deal to fix just by the virtue of the system handling it automatically.

**Comment by maddoodles** [comment]
> just that simple typos (especially ones that involve math) aren't a huge deal to fix just by the virtue of the system handling it automatically.
That's the thing, I'm not 100% convinced they are typos. 
In my personal opinion, I'd stick to what's in the books even if they seem wrong, otherwise, surely you're just creating a personal errata anyway? It's up to you at the end of the day though, although I do plan to try and confirm whether those values are mistakes or not now, as some of the changes that would be made have relatively large ramifications for encounters.
As you say, this isn't that hard to adjust on the GM end, as long as updates don't reset everything.

Thank you for your time, I'll go ahead and close the issue.

**Comment by moo-man** [comment]
Based on producer input, these are most likely typos. There was some interest in an errata so a full list would be appreciated if you have it, but of course no obligations to provide one.
