### ISSUE TITLE
[WRath & Glory: Litanies of the Lost] Grim Harvest Map not the same as in the physical book

### ISSUE THREAD

**Issue by moo-man** [moo-man/WrathAndGlory-FoundryVTT#179]
buildings different sizes and placement<br/>**From**: Michael Mars#8075<br/>wrath-and-glory: 4.0.2

**Comment by moo-man** [comment]
Had to use this map, was the best unlabeled version

**Comment by MichaelMarsGaming** [comment]
Labels don't matter on that map as the PCs learn the names of every location on planet fall. Map is really wrong, most buildings are the wrong size and in the wrong locations.
