### ISSUE TITLE
[Wrath & Glory System] Keywords field in Item Sheet is a String

### ISSUE THREAD

**Issue by RadCrusher** [moo-man/WrathAndGlory-FoundryVTT#184]
So I am trying to use the generic item filters from the archetype wargear tab. I managed to get the filters to filter according to type, value and rarity, however the keyword one doesn't seem to work or I don't know how to designate it.

I am not using any of the official data modules and have created every item from scratch and all of the items(weapon, gear, armour types) in their Keyword field only take Strings. I can't drag Keyword type items on to Item windows as it seems to do nothing in my case. 

When I checked the filter script seems to check if the item has Keyword type, but since all of my items only have Strings and not actual Keyword type items it just skips the section.

**Version Numbers**
Foundry: Version 10 Build 288
wrath-and-glory: 4.0.2
wng-forsaken: n/a
wng-litanies: n/a

**Comment by moo-man** [comment]
Sorry for the late reply, but you can accomplish this by using `hasKeyword` in the filter property.



![Image](https://user-images.githubusercontent.com/28637157/213835619-e4a1d92d-89aa-42fe-9b11-cd9d28a06e40.png)

**Comment by RadCrusher** [comment]
Ah, so that's how I can do it. Thank you.
