### ISSUE TITLE
[Wrath & Glory System] Reroll not working for damage

### ISSUE THREAD

**Issue by moo-man** [moo-man/WrathAndGlory-FoundryVTT#185]
right clicking and using wrath / ruin to reroll weapon damage instead rerollsthe test. Can not reroll damage whatsoever<br/>**From**: Michael Mars#8075<br/>wrath-and-glory: 4.0.2

**Comment by moo-man** [comment]
Not planned, just click roll damage again

**Comment by MichaelMarsGaming** [comment]
that doesn't keep the successes of the original roll though
