### ISSUE TITLE
[Wrath & Glory: Core Module] On Firefox the cover.webp image part of the standard assets does not render

### ISSUE THREAD

**Issue by moo-man** [moo-man/WrathAndGlory-FoundryVTT#194]
When I use Firefox 108+ on Windows or MacOS, the default scene in the compendium using the cover.webp image is black. When I create new scene with the same image from the assets directory, it is black again. Other images in .webp format are ok, there is something wrong with the cover.webp file. 

No errors in the console. On MS Edge all is good. I don't use Chrome, but I presume same. 

FTVTT is 10.291

W&G systme is 4.0.2

Module is whatever is available now in the repository, don't see version.  <br/>**From**: Valyar#<br/>wrath-and-glory: 4.0.2

**Comment by r-valyar** [comment]
Here is screenshot of the bug from Firefox
![image](https://user-images.githubusercontent.com/63558984/209404167-73cd5275-5d29-436c-962e-25f9bf1d600b.png)

All OK on MS Edge

![image](https://user-images.githubusercontent.com/63558984/209404240-e0235c48-72f5-4fd2-ac50-9351b88b3f24.png)

**Comment by moo-man** [comment]
Could not reproduce. Please include any console errors you see.

**Comment by r-valyar** [comment]
There are no console errors :/

**Comment by moo-man** [comment]
Well, the image is just a webp image like the others, and there's no real reason it shouldn't render. I assume this is some issue with your firefox client. Closing until there's any more information to act upon.

**Comment by r-valyar** [comment]
@moo-man the root cause of the issue on Firefox is the browser unable to display image when width is more than 8k pixels. I guess this is for the canvas only, because there are no problems with the same image on the world's login screen (I presume you use the same image there). 

So we know the root cause now.

**Comment by moo-man** [comment]
It definitely can display more than 8k, as I mentioned above, I can't reproduce this issue, it works fine when I use Firefox.
