### ISSUE TITLE
Module Initialization and Setup routines does not create scenes within a folder

### ISSUE THREAD

**Issue by moo-man** [moo-man/WrathAndGlory-FoundryVTT#200]
On W&G System and Module that are up to date, when the module is Initialized, the scenes are not created. Everything else looks like is set up properly, but scenes are missing. I am not able to manually import them as they don't appear as compendium items. <br/>**From**: Valyar#2907<br/>wrath-and-glory: 4.0.2

**Comment by r-valyar** [comment]
![image](https://user-images.githubusercontent.com/63558984/214528960-39451591-e1ac-4787-8706-0ce7d29528f9.png)

This is error found in the console. 

There is second one related to actors, but it looks they are created (don't have time to cross-check with PDF if they are properly established)

![image](https://user-images.githubusercontent.com/63558984/214529083-26591339-3c5d-499e-8e84-cc87fdc7adf7.png)

**Comment by r-valyar** [comment]
![image](https://user-images.githubusercontent.com/63558984/214536430-d9376267-5601-41a8-ba0e-7d73663dfe43.png)
