### ISSUE TITLE
Some feature requests

### ISSUE THREAD

**Issue by nottsknight** [moo-man/WrathAndGlory-FoundryVTT#21]
Thanks for your work on this, alongside the impressive WFRP system! Some requests for new features that hopefully aren't too out there:

- [x] Quantity field for all gear (especially useful for tracking grenades)
- [x] Field on Combat tab for tracking Reloads
- [x] Rows for Abilities/Psychic Powers/etc should grow vertically to show all the text in the Effect field
- [x] Add a 'Force Weapon' category to allow automatically adding Willpower to Damage if the character has the Psyker keyword

**Comment by thul** [comment]
Reload are done (albeit kinda odd) via the Ammo item type. There you can say how much of it you have. I agree it can be done better.
