### ISSUE TITLE
wng-core: Actors, Items and Scenes not imported.

### ISSUE THREAD

**Issue by farling42** [moo-man/WrathAndGlory-FoundryVTT#220]
**Describe the bug**
When running the importer for the W&G Core Module, no Actors, Items or Scenes are imported. Only the Journal Entries and RollTables are imported into the world.

**To Reproduce**
- Create a new W&G world
- Start the world
- Enable the W&G Core Module
- Accept the button to import the data
- Observe that the Actor, Scene and Item world tabs are empty.

**Screenshots**

**Version Numbers**

Foundry: 10.291
wrath-and-glory: 4.2.0
wng-core: 3.1.0

**Comment by moo-man** [comment]
This is intentional, see the patch notes 
https://github.com/moo-man/WrathAndGlory-FoundryVTT/releases/tag/4.2.0

**Comment by farling42** [comment]
I just noticed the latest comments in the release notes. However the module itself still says that it has those items which are going to be imported.

The character sheet is not finding the relevant items when clicking on the Species, Faction and Archetype buttons.

**Comment by moo-man** [comment]
Clicking on those fields in the sheet looks for owned items. The message is simply stating the actor does not have the respective item.

**Comment by farling42** [comment]
Thanks for that. I misunderstood what clicking them I did. I was expecting a list of available items to appear.
