### ISSUE TITLE
[Wrath & Glory System] Dice Symbols Not Rendering Correctly

### ISSUE THREAD

**Issue by moo-man** [moo-man/WrathAndGlory-FoundryVTT#230]
After upgrading Foundry to v11, all the dice rolls and images are gone<br/>**From**: mathsteck@gmail.com<br/>wrath-and-glory: 4.2.1

**Comment by mathsteck** [comment]
This is how the the dice rolls look in v11:
![image](https://github.com/moo-man/WrathAndGlory-FoundryVTT/assets/3390366/696cab71-e9e8-4770-bea3-55388a268ba7)
This is how the dice rolls used to look (still missing the Approved Seal though):
![image](https://github.com/moo-man/WrathAndGlory-FoundryVTT/assets/3390366/7f73183d-7115-4709-8be5-41c9794d0934)

**Comment by mathsteck** [comment]
![image](https://github.com/moo-man/WrathAndGlory-FoundryVTT/assets/3390366/b8cf98d3-b363-4b68-a9b0-8455460d3b6f)

**Comment by mathsteck** [comment]
It is not possible to enable it because it completely disappeared from the list:
![image](https://github.com/moo-man/WrathAndGlory-FoundryVTT/assets/3390366/06efc8f9-ee97-44e6-bfe1-3cd59847f24a)

**Comment by mathsteck** [comment]
That worked, thanks 👍
