### ISSUE TITLE
[Wrath & Glory: Forsaken System Module] Missing Abilities

### ISSUE THREAD

**Issue by moo-man** [moo-man/WrathAndGlory-FoundryVTT#239]
Character archetypes abilities are not packaged into the module.<br/>**From**: horvathdanielrichard@gmail.com<br/>wrath-and-glory: 5.0.0

**Comment by moo-man** [comment]
No modules enabled

**Comment by adracea** [comment]
This report is actually correct, `Archetype Abilities`, `Special Abilities`(see Ogryn/Ratling/Kroot Species), `Psychic Powers` seem to be missing from all archetypes and species.

**Comment by moo-man** [comment]
This should be fixed now
