### ISSUE TITLE
Drag & Drop Archetype not working

### ISSUE THREAD

**Issue by Davina42** [moo-man/WrathAndGlory-FoundryVTT#243]
**Describe the bug**
Drag & Drop of archetypes doesn't work anymore. I tried from companions, from imported items, I tried deactivating every module, and even reinstalling the system. Nothing is working

**To Reproduce**
Try to drag & drop an archetype item on an actor.

**Version Numbers**

Foundry:  V11 Build 315 Stable
wrath-and-glory: 5.0.1
wng-forsaken: Not installed
wng-litanies: Not installed

**Comment by moo-man** [comment]
Do you get console errors? And if so can you provide them?

**Comment by moo-man** [comment]
I cannot reproduce this issue. If you can provide precise reproduction steps or console errors, it may help diagnosing the problem.

**Comment by Davina42** [comment]
I did have a look at my local installation, which will also give this error. I get the following error message via console:

![image](https://github.com/moo-man/WrathAndGlory-FoundryVTT/assets/62229846/79b061bc-4e0f-4580-abff-7a53f9b60af3)

**Comment by moo-man** [comment]
What about precise reproduction steps, like what archetype, where you're dragging it from, etc.

**Comment by Davina42** [comment]
I created the Inquisitor Archetype myself (but it happens with every archetype, even those which worked a few days ago). I then create a new actor, in this case an agent. I drag the Inquisitor archetype from the item tab, get the popup for character creation and click yes. Nothing happens. Then I tested to put the archetypes into a companion, and drag them from there, which will also not work.

**Comment by moo-man** [comment]
Perhaps export the archetype and post it here and I can see what might be wrong, as for the others that used to work, were they also custom? I can't find any issues with the ones from the official modules.

**Comment by Davina42** [comment]
I do not have the official modules, I create every archetype myself. I will export one which worked a few days ago:
[fvtt-Item-space-marine-scout-ZQeLwqb6aCCIGsGR.json](https://github.com/moo-man/WrathAndGlory-FoundryVTT/files/13788503/fvtt-Item-space-marine-scout-ZQeLwqb6aCCIGsGR.json)

**Comment by moo-man** [comment]
The issue here is that the Species item linked to your Archetype does not exist. It was deleted or the source item was removed. Simply drag and drop the one you want onto the Archetype to re-link it.

Re-open the issue if the problem persists.
