### ISSUE TITLE
Just purchased, unable to load in current Foundry Version

### ISSUE THREAD

**Issue by Liefwind** [moo-man/WrathAndGlory-FoundryVTT#254]
**Describe the bug**
I just purchased both Foundry and The Warhammer 40,000: Wrath & Glory, Foundry Core Module.  It says to search for game system: Wrath and Glory.  It isn't available.  I found your JSON file and tried to load that, but it says its incompatible with the current version of Foundry.  Do I need to request a refund or is an update in works?

**To Reproduce**
load current foundry build, attempt to install Wrath and Glory system

**Version Numbers**
Foundry: Foundry version 12, build 324.  
wrath-and-glory: wrath-and-glory: No idea on the wrath version, the game system isn't available to load. Tried to load your latest JSON from here,

**Comment by moo-man** [comment]
You simply need to use v11 until I can update the system and modules

**Comment by moo-man** [comment]
Fixed via https://github.com/moo-man/WrathAndGlory-FoundryVTT/commit/acca7303e54fc0e607f6e2b4d00b7d252bea80fe
