### ISSUE TITLE
Sororitas Power Armour

### ISSUE THREAD

**Issue by pagan1313** [moo-man/WrathAndGlory-FoundryVTT#258]
**Describe the bug**
When a players wears the Sororitas Power Armour. the strength stat is not correct. For example the base stat for STR is 5, when the player wears the Sororitas Power Armour, the str is changed to 52.

**To Reproduce**
Wear the Sororitas Power Armour armor.

**Screenshots**

Foundry:
wrath-and-glory:
church-of-steel

<img width="692" alt="Screenshot 2024-07-06 at 8 22 03 AM" src="https://github.com/moo-man/WrathAndGlory-FoundryVTT/assets/174884165/5391c5f9-166d-4941-b19e-dc5abbe998b7">
<img width="694" alt="Screenshot 2024-07-06 at 8 21 55 AM" src="https://github.com/moo-man/WrathAndGlory-FoundryVTT/assets/174884165/f684358a-ecdd-41d4-8462-393991781bb7">

**Comment by Silentdarkness12** [comment]
This is a problem I mentioned to him on discord. The same glitch applies to just about any item that enhances stats with an effect. Apparently it's concatenating rather than adding or subtracting.
