### ISSUE TITLE
No longer able to install or update the system in Foundry (5.0.2)

### ISSUE THREAD

**Issue by yakuzadave** [moo-man/WrathAndGlory-FoundryVTT#261]
**Describe the bug**
> A clear and concise description of what the bug is.
- No longer able to install or update the system in Foundry, instead the following error is shown:
```
Metadata validation failed for module "wng-core": Cannot read properties of undefined (reading '0')
```

**To Reproduce**
> If applicable, provide steps to reproduce this issue

- Try and install/update from `Game Systems` in Foundry VTT
- Try and install directly with the manifest

**Version Numbers**
PLEASE PROVIDE YOUR FOUNDRY, SYSTEM, and MODULE VERSIONS (where applicable) 

Foundry: v 12 Build 392
wrath-and-glory: 5.0.2
wng-forsaken: NA
wng-litanies: NA

**Comment by moo-man** [comment]
You likely need to reinstall Foundry. If you have questions, I recommend consulting the Foundry discord.

Closing as this is not actually related to the system or modules.
