### ISSUE TITLE
[Wrath & Glory System] Ascension Packages Not Subtract XP

### ISSUE THREAD

**Issue by moo-man** [moo-man/WrathAndGlory-FoundryVTT#262]
When dragging and dropping an ascension package onto a character sheet, the package cost is ignored and not reflected in the spent XP field.<br/>**From**: jimmybolter<br/>wrath-and-glory: 5.1.5<br/>wng-core: 4.0.5<br/>wng-cos: 4.0.0<br/>wng-forsaken: 4.0.3<br/>wng-litanies: 4.0.2<br/>wng-records1: 4.0.2<br/>Active Modules: combat-hp-display, dd-import, df-settings-clarity, dice-calculator, dice-so-nice, drag-ruler, dragupload, easy-target, enhanced-terrain-layer, find-the-culprit, force-client-settings, foundry-combat-focus, fvtt-party-resources, hiddensoundtracks, lib-wrapper, monks-bloodsplats, monks-hotbar-expansion, monks-little-details, monks-scene-navigation, monks-tokenbar, quickscale, remote-highlight-ui, scene-packer, settings-extender, socketlib, terrain-ruler, token-z, wng-apocrypha, wng-dragruler

**Comment by pagan1313** [comment]
We are experiencing this as well. It's causing problems because we can not adjust the total experience.
