### ISSUE TITLE
[Wrath & Glory: Core Module] Minor:  Character sheet avatar doesn't fit properly

### ISSUE THREAD

**Issue by alemanym** [moo-man/WrathAndGlory-FoundryVTT#264]
The avatar in the character sheet does not fit the space correctly.
I think the CSS property **fit-content** of the image would be **cover** instead of **contain**.

Config:
- wrath-and-glory: 5.1.5
- wng-core: 4.0.6

**Comment by moo-man** [comment]
`contain` is intended, `cover` would not be desirable. 

cover:
![image](https://github.com/user-attachments/assets/dcdcfc0c-3e09-401b-8f9e-6166e52dc690)

contain:
![image](https://github.com/user-attachments/assets/93cde63b-9e1f-481a-bcf9-453a7c870b00)
