### ISSUE TITLE
[Core Module] Species and Faction button dont work

### ISSUE THREAD

**Issue by moo-man** [moo-man/WrathAndGlory-FoundryVTT#269]
I can clickon that buttons but after that nothing happens.
I cannot select the character's background modifiers and see the maximum atributes for my species<br/>**From**: gruby.gra@o2.pl<br/>wrath-and-glory: 5.1.5<br/>wng-core: 4.0.6<br/>wng-cos: 4.0.0<br/>wng-forsaken: 4.0.3<br/>wng-records1: 4.0.2<br/>Active Modules: PolishCore, colorsettings, crossblade, dice-so-nice, drag-ruler, easy-notes, enhanced-terrain-layer, fvtt-party-resources, lib-wrapper, popout, settings-extender, socketlib, terrain-ruler, tile-scroll, wng-dragruler, wng-system-translation-fr, forge-vtt, forge-vtt-optional

**Comment by moo-man** [comment]
Species and Faction are Items and can be added to Actors via drag+drop.

**Comment by GrubyGra** [comment]
I know this, but in older versions of the core module, if I drag and drop it onto my character sheet, I can open it with a button on the character sheet and easily select the character modifiers in the faction.
now this is not possible.
