### ISSUE TITLE
the main module has been broken

### ISSUE THREAD

**Issue by GrubyGra** [moo-man/WrathAndGlory-FoundryVTT#276]
I can't use the character cards because the main module must have been damaged

I tried restarting the game several times but nothing changes 

Even running in safe mode doesn't help

![image](https://github.com/user-attachments/assets/3bde917a-eab4-403c-aec7-fa7ef4330113)

![image](https://github.com/user-attachments/assets/8d4a7247-2b61-4427-b880-614e4a79c235)

![image](https://github.com/user-attachments/assets/b98a6c8d-9701-47fb-aef5-b4f88f91d9e0)

**Comment by moo-man** [comment]
Disable the Warhammer Library module. It shouldn't be used until it's integrated into the v12 specific release of Wrath & Glory
