### ISSUE TITLE
my game crashed after the last update

### ISSUE THREAD

**Issue by GrubyGra** [moo-man/WrathAndGlory-FoundryVTT#277]
After the last module update (5.1.6) , I cannot enter the game as GM

Safe mode doesn't help

After loading screen i see this 

![image](https://github.com/user-attachments/assets/24b53fca-1edd-4da4-b13e-e3eee5b320a0)

on the previous version the game also stopped working

**Comment by moo-man** [comment]
Please don't create multiple issues about the same topic. 

Did you do what I suggested in the previous issue?

**Comment by GrubyGra** [comment]
yes, I did what you said and I was able to use the module normally

However, after the update, I completely lost access to the game, even though I didn't change any settings

Previously, safe mode allowed me to at least go in and change enabled modules, but now that's not possible

**Comment by moo-man** [comment]
Do you see any console errors? 

Also you refer to 1.5.6, that's not a version number I recognize for anything related to warhammer

**Comment by GrubyGra** [comment]
my bad sorry 
I meant version 5,1,6

![image](https://github.com/user-attachments/assets/8d31d4d0-55ef-4206-ad34-665de3b4e37c)

sorry, I don't know anything about programming

**Comment by GrubyGra** [comment]
I haven't tried it yet because yesterday, before the update, everything worked after turning off the module you mentioned earlier
