### ISSUE TITLE
Compatibility with Foundry VTT version 12

### ISSUE THREAD

**Issue by Creos945** [moo-man/WrathAndGlory-FoundryVTT#283]
Is it possible to have compatibility with FVTT version 12

**Comment by moo-man** [comment]
The system has been compatible since 5.0.3

**Comment by Creos945** [comment]
Foundry say this message "last verified for version 11" "compatibility risk". I'm using the 516 version on Foundry 12 build 331

**Comment by moo-man** [comment]
Yeah, that's normal. The system is currently meant for V11 but has some V12 compatibility added

**Comment by Creos945** [comment]
Ok, thanks a lot !
