### ISSUE TITLE
Wrath & Glorty system is missing a thumbnail

### ISSUE THREAD

**Issue by InnilToo** [moo-man/WrathAndGlory-FoundryVTT#287]
**Describe the bug**
System is missing a thumbnail.

**To Reproduce**
1. Launch FVTT.
2. Open Game Systems tab.
3. Look at the missing thumbnail.

**Screenshots**
<img width="350" alt="image" src="https://github.com/user-attachments/assets/b0ba8f69-3f30-4533-8dd4-df0e3f7b97ec">

**Version Numbers**

Foundry: v12 Build 331
wrath-and-glory: 5.1.7

**Comment by moo-man** [comment]
It uses a thumbnail provided by the core module, which is intentional
