### ISSUE TITLE
Cannot enter values into agent & threat sheets

### ISSUE THREAD

**Issue by hoganton** [moo-man/WrathAndGlory-FoundryVTT#3]
This might be a stupid question, but I'm totally new to foundry so maybe it isn't a problem and only my limited knowledge. 

If I create a new "agent" actor and want to edit it, I'm not able to change/enter any values into the stats, skills nor combat traits cells. In the threat sheet are also a lot of cells I cannot edit, but fewer than in the agent sheet. 

Am I supposed to crate the characters in another way or an I just too dumb?

Btw, when I looked at the code I found that the corruption ` "current": 0` for the threat actor on line 252 & 253 is listed twice. I don't know if that's a problem.

**Comment by eidlehands** [comment]
I found that you have to go into the ADVANCES tab to enter the values for stats and skills.

**Comment by JUNGLE-FEVER** [comment]
I'm still having this same problem for threats. Everything highlighted in yellow cannot be edited.
![Capture](https://user-images.githubusercontent.com/89503801/130730419-c1cc57e7-9691-4ecf-9408-a594c1f9481f.PNG)
