### ISSUE TITLE
Glory and Ruin trackers attached to sidebar

### ISSUE THREAD

**Issue by nottsknight** [moo-man/WrathAndGlory-FoundryVTT#32]
As title! (See how Momentum is tracked in the Star Trek Adventures system for an idea of what I mean)

**Comment by moo-man** [comment]
You specify attached to the sidebar, however I've already implemented an initial version of this in a separate window
![image](https://user-images.githubusercontent.com/28637157/128773672-dd64995a-5ab6-4c84-a557-a33f61e7f149.png)

Is it important to be attached to the sidebar?

**Comment by nottsknight** [comment]
Ah fun, no I imagine that'd work fine, I was just going off of a solution I'd already seen :)
