### ISSUE TITLE
Threat Sheet Issues

### ISSUE THREAD

**Issue by JUNGLE-FEVER** [moo-man/WrathAndGlory-FoundryVTT#39]
The Threat sheets don't update the Defense, Resilience, Shock, Awareness, Determination, Wounds, Conviction, and Resolve do not update automatically and cannot be edited manually. 

![threat](https://user-images.githubusercontent.com/89503801/131239221-c543a356-35ca-4f79-aea0-2df3f0915a4b.PNG)

**Comment by Novabjorn** [comment]
Yep, ran into this as well this morning. Might have to use agent sheet for my threats this week. If you want to increase wounds for specific threats it looks like the best way to do it is passive effects:
![image](https://user-images.githubusercontent.com/12959299/131360146-06dab9cf-1819-4b07-90fc-e3880e621c9c.png)

**Comment by moo-man** [comment]
I hope to get a fix out today for this

**Comment by JUNGLE-FEVER** [comment]
You're awesome. thanks
