### ISSUE TITLE
Issue with ampersand (&) in game system's title

### ISSUE THREAD

**Issue by r-valyar** [moo-man/WrathAndGlory-FoundryVTT#40]
There is issue with the ampersand in the system's title in the official game systems list:

![image](https://user-images.githubusercontent.com/63558984/131328114-3b5b7b8c-fe4a-4be8-a49b-d97dbe039c48.png)

**Comment by moo-man** [comment]
I do not control how text is displayed in the Foundry menus, and will need to be resolved by them.
