### ISSUE TITLE
Resilience and Armor Value

### ISSUE THREAD

**Issue by JUNGLE-FEVER** [moo-man/WrathAndGlory-FoundryVTT#41]
Recommend there is a split between armor and base resilience so to better understand the armor that may be affected by weapon penatration more quickly. Simlar to the way R20's sheet does it. 
![1](https://user-images.githubusercontent.com/89503801/131456416-84529a00-c051-43d6-b79e-c2af54cdda30.PNG)

**Comment by thul** [comment]
Keep in mind that according to the rules only the highest armor (AP) value is used. Also this screenshot is from the old rules, since C7's rules don't use "soak" anymore

**Comment by kaal-dam** [comment]
I would also add that since C7 version weapon penetration affect Resilience as a whole with or without armor

**Comment by thul** [comment]
@moo-man i think this can be closed? currently armor rating is added to resilience and AP subtracts from that (wether you have armor or not). So works as intended
