### ISSUE TITLE
Strength Attribute lowered when adjusting the combat tab stats.

### ISSUE THREAD

**Issue by Novabjorn** [moo-man/WrathAndGlory-FoundryVTT#42]
Modifying the stats (wounds/shock/defense/etc.) on the combat tab lowers the Strength attribute by 1. This doesn't happen when modifying the wounds/shock on the token.
![Strength_Bug](https://user-images.githubusercontent.com/12959299/131848115-6d13d399-5bc9-43c6-9a49-3206c7c8408e.gif)

**Comment by moo-man** [comment]
I cannot reproduce this, do you have any active effects on the actor?

**Comment by Novabjorn** [comment]
It's happening across all actors and threats. I'll turn of my modules, and if that doesn't fix it i'll upgrade foundry and see if any of those fixes it.

**Comment by Novabjorn** [comment]
Okay, I've tried both turning of all modules, and upgrading to 8.9 from 8.7 and it's still doing this. It happens on a fresh character sheet with no effects.

**Comment by Novabjorn** [comment]
Looks like this is happening when I change any data field (Wrath, Species, Quote, etc.)

**Comment by moo-man** [comment]
Could you contact me on discord and perhaps we can figure it out
