### ISSUE TITLE
Idea for enhancing roll in chat

### ISSUE THREAD

**Issue by kaal-dam** [moo-man/WrathAndGlory-FoundryVTT#46]
Right now when a roll is made in chat to reroll it, we need to open the character sheet of the associated character and use the reroll button, it isn't really intuitive and may be likely improved by a right click option or a button on the roll UI in the chat.

Additionally right now when an attack roll is made the damage roll is automatically rolled, thus not taking into account possible shift for extra ED or other rules that may apply, same as previously a right click option or a button in the chat UI of the roll may be beneficial to open the damage window.

Thank you for your time.

**Comment by moo-man** [comment]
Yes the reroll button has been removed and a right click chat reroll has replaced it

**Comment by kaal-dam** [comment]
nice news @moo-man have you any plan comming about the second point ?

**Comment by moo-man** [comment]
I haven't accounted for damage changes yet but it's planned.
