### ISSUE TITLE
Speed Automation

### ISSUE THREAD

**Issue by dragoon1000** [moo-man/WrathAndGlory-FoundryVTT#59]
Speed can be affected by various items, augmetics and abilities. It might be worth automating a little so my space marine can become one with the speed force with a little less math.
Things known to affect speed:
Species
Being an Evil Sunz Ork (+1 Speed)
Uncanny [Trait] (can take +1 speed)
Bulky(X) (Reduce speed by x)
Magboots (minus 3 speed while in use)
Augmetic Legs (+2 speed)
Malformed Leg Extra appendage (-1 speed)
Equidae Aberration (+1 Speed)
Canidae Aberration (+1 Speed)
Vile Alacrity Mutation (+2 Speed)

Fun Fact: Being a white scar with a speed of 15 means you can charge something 45 away meaning you can charge farther than most weapons in the game can fire.

**Comment by moo-man** [comment]
Bulky is the only non-item in this list, have you looked at the effects on the items you mentioned and they are lacking a speed effect?
