### ISSUE TITLE
[Wrath & Glory System] Glory And Ruin Counter 

### ISSUE THREAD

**Issue by moo-man** [moo-man/WrathAndGlory-FoundryVTT#86]
For me as GM the counter works fine but for the rest of the group it will show wrong, almost random numbers. Lets say that the group has 5 Glory. One player says that he/she sees that they have 4 Glory, another says they have 2 and a third player says that they have 5 glory. And when they gain or spend Glory it start all over again.<br/>**From**: Sparky #9014<br/>wrath-and-glory: 3.2.0<br/>wng-core: 1.0.2

**Comment by kaal-dam** [comment]
Had this one happening last session for my group, manually updating the counter server side on foundry updated it for all my players

**Comment by agraubert** [comment]
My friends and I seem to be having a related issue. Our Glory and Ruin counters are in sync, but they only go up. Reducing the counter or changing the number in the box does not sync out and is a local-only change. However even if anyone makes a change, when someone _increases_ the count again, everyone's count goes up
