### ISSUE TITLE
Is this project active?

### ISSUE THREAD

**Issue by Rudithus** [moo-man/WrathAndGlory-FoundryVTT#9]
Hey, thanks for developing this. I've been looking for a foundry system for a warhammer 40k rpg for sometime and I just found out about this. I'm wondering if you are still developing this, or if you have plans to continue adding features.

**Comment by moo-man** [comment]
My aim is for it to be active, but currently I'm spread thin, as I'm involved in 5+ systems, mainly wfrp and it's official modules

**Comment by Rudithus** [comment]
I see, thanks for answering.
