### ISSUE TITLE
[Wrath & Glory System] Single 6 on multiple wrath dice causes a wrath critical

### ISSUE THREAD

**Issue by moo-man** [moo-man/WrathAndGlory-FoundryVTT#94]
If multiple wrath dice are rolled, it should take a 6 on all wrath dice to score a critical.

Core Rule Book p194
Church of Steel: p31, p46<br/>**From**: @disgeni<br/>wrath-and-glory: 3.3.0<br/>wng-core: 1.1.0

**Comment by thul** [comment]
@moo-man I believe this is already fixed in the develop branch?

**Comment by thul** [comment]
https://github.com/moo-man/WrathAndGlory-FoundryVTT/pull/112 fixes this
